"""
services/integrity_engine.py
=============================================================================
Sterling AI — Integrity Engine v1.0 (Sprint 3)
=============================================================================
The FAIR cheating detection system.

Core Philosophy:
  - NO binary guilty/not-guilty flag.
  - Uses a continuous integrity_score (100 = clean, 0 = definite cheat).
  - Every deduction requires MULTIPLE correlated signals.
  - The "Human Firewall": the algorithm flags, humans decide.
  - Genuine candidates are protected through grace periods and challenge-gating.

Score Bands:
  90-100 → CLEAN         (auto-advance to next round)
  70-89  → BORDERLINE    (human review recommended)
  50-69  → FLAGGED       (human review required before advancing)
  0-49   → HIGH RISK     (strong evidence; human must approve any advance)
=============================================================================
"""
import re
import logging
from datetime import datetime, timezone
from utils.ist_time import ist_isoformat
from typing import Optional

logger = logging.getLogger("IntegrityEngine")


# ── Signal Registry (what gets deducted and why) ─────────────────────────────
# Each signal has a weight and a human-readable reason.
# Weights are conservative by design — a single signal rarely crosses a band.

SIGNAL_WEIGHTS = {
    # Tab / focus violations (proctoring)
    "tab_switch_1st":          0,   # 1st tab switch → grace period, no deduction
    "tab_switch_2nd":          8,   # 2nd tab switch → mild deduction
    "tab_switch_3rd_plus":    15,   # 3rd+ tab switch → significant deduction
    "devtools_detected":      12,   # Browser devtools opened during interview

    # Answer syntax signals
    "gpt_syntax_confirmed":   20,   # CONFIRMED ChatGPT syntax (requires challenge fail too)
    "gpt_syntax_suspected":    0,   # Suspected only → fires challenge, NO deduction yet
    "resume_challenge_fail_1":  0,  # 1st resume claim failure → no deduction (grace)
    "resume_challenge_fail_2": 18,  # 2nd consecutive failure on SAME claim → deduction

    # Behavioral signals (weighted low because individually meaningless)
    "zero_filler_words":       5,   # No natural speech disfluencies at all (scripted?)
    "perfect_structure_every": 8,   # Every answer is robotically structured (STAR/format)
    "abnormally_fast_wpm":    10,   # >280 WPM sustained (reading from script)
    "abnormally_low_wpm":      0,   # <30 WPM (confusion, not cheating)
}

# ── GPT / AI Syntax Detector ─────────────────────────────────────────────────
# These patterns are strong signals of AI-generated text in a spoken context.
# A SINGLE hit is "suspected" (fires challenge question, no score deduction).
# Confirmed = suspected + failed the challenge.

GPT_SYNTAX_PATTERNS = [
    # Classic opening phrases
    r"\bCertainly[,!]?\b",
    r"\bAbsolutely[,!]?\b",
    r"\bGreat question\b",
    r"\bOf course[,!]?\b",
    r"\bSure[,!]? here('s| is)\b",
    # Structured enumeration phrases
    r"\bFirstly\b.{0,80}\bSecondly\b",
    r"\bIn conclusion\b",
    r"\bTo summarize\b",
    r"\bIn summary\b",
    r"\bIt is worth noting that\b",
    r"\bIt is important to note that\b",
    r"\bFurthermore\b.{0,80}\bMoreover\b",
    # Perfect "there are N types" openers
    r"\bThere are (three|four|five|several|multiple) (types|ways|approaches|key|main)\b",
    # Textbook definitions
    r"\bis defined as\b.{0,50}\bwhich means\b",
    r"\bIn the context of\b.{0,30}\bwe can say that\b",
]

# ── Resume Claim Extractor ───────────────────────────────────────────────────
# Extracts specific, challengeable claims from a resume for the AI to probe.
# Returns a list of strings that can be injected into the question prompt.

def extract_challenge_targets(resume_data: dict) -> list[str]:
    """
    Given resume parsed data (from parse_and_score_resume), extract specific
    claims the AI should challenge the candidate on during the interview.

    Returns up to 5 challenge targets formatted for prompt injection.
    """
    targets = []

    # From extracted projects
    for proj in resume_data.get("extracted_projects", [])[:3]:
        if len(proj) > 20:  # Skip trivial/placeholder descriptions
            targets.append(f"Resume claim — Project: '{proj[:120]}'")

    # From extracted skills (pick the most specific ones)
    skills = resume_data.get("extracted_skills", [])
    # Prioritize deep technical skills over generic ones
    deep_skills = [s for s in skills if any(
        w in s.lower() for w in
        ["kubernetes", "kafka", "tensorflow", "pytorch", "foc", "bms", "kalman",
         "microservices", "graphql", "rust", "go", "cuda", "simulink", "can protocol"]
    )]
    for skill in deep_skills[:2]:
        targets.append(f"Resume claim — Expertise in: '{skill}'")

    # From interview_focus_areas (already generated by resume_engine)
    for area in resume_data.get("interview_focus_areas", [])[:2]:
        targets.append(f"Probe area from resume: '{area}'")

    if not targets:
        targets.append("No specific resume claims available — assess stated skills only.")

    return targets[:5]


def build_challenge_prompt_injection(challenge_targets: list[str]) -> str:
    """
    Formats challenge targets into a prompt injection block for prompt_engine.py.
    This text is injected into build_question_prompt's resume_section.
    """
    if not challenge_targets or challenge_targets[0].startswith("No specific"):
        return ""

    lines = "\n".join(f"  - {t}" for t in challenge_targets)
    return (
        f"\n\n⚡ RESUME CHALLENGE TARGETS (CRITICAL — ASK ABOUT THESE):\n"
        f"{lines}\n"
        f"You MUST ask at least one question that directly probes a claim above. "
        f"Ask for the exact implementation detail, not a textbook definition. "
        f"If the candidate cannot explain a claimed skill at a basic level, "
        f"note this but do NOT penalize them for a single weak answer."
    )


# ── GPT Syntax Detection ─────────────────────────────────────────────────────

def detect_gpt_syntax(transcript: str) -> dict:
    """
    Scans a candidate's answer transcript for AI-generated text patterns.

    Returns:
        {
            "suspected": bool,          — True if ≥1 pattern matched
            "matched_patterns": [str],  — Human-readable list of what matched
            "pattern_count": int        — Number of distinct patterns matched
        }

    IMPORTANT: A single "suspected" hit does NOT score-penalise the candidate.
    The caller must fire a challenge question and only deduct if challenge fails.
    """
    if not transcript or len(transcript.strip()) < 30:
        return {"suspected": False, "matched_patterns": [], "pattern_count": 0}

    matched = []
    for pattern in GPT_SYNTAX_PATTERNS:
        if re.search(pattern, transcript, re.IGNORECASE):
            matched.append(pattern.replace(r"\b", "").replace(r".{0,80}", "..."))

    return {
        "suspected": len(matched) >= 1,
        "matched_patterns": matched[:5],
        "pattern_count": len(matched),
    }


# ── Core Integrity Scorer ────────────────────────────────────────────────────

class IntegrityEngine:
    """
    Maintains integrity state across the entire interview for one candidate.
    Call record_signal() throughout the interview, then compute_final() at end.
    """

    def __init__(self, candidate_id: str):
        self.candidate_id = candidate_id
        self.score = 100              # Starts at 100 (clean), only goes down
        self.signals: list[dict] = [] # Audit log — every signal recorded
        self._tab_switch_count = 0
        self._gpt_suspected_count = 0
        self._gpt_challenge_pending = False
        self._resume_fail_streak: dict[str, int] = {}  # skill → consecutive fails

    def record_signal(self, signal_key: str, metadata: Optional[dict] = None) -> dict:
        """
        Record an integrity signal event.
        Returns {"deducted": int, "new_score": int, "note": str}
        """
        metadata = metadata or {}
        ts = ist_isoformat()

        # ── Special logic for tab switches ───────────────────────────────────
        if signal_key == "tab_switch":
            self._tab_switch_count += 1
            if self._tab_switch_count == 1:
                # First switch: grace period — log only, zero deduction
                actual_key = "tab_switch_1st"
                note = "First tab switch (grace period). No deduction. Warning shown."
            elif self._tab_switch_count == 2:
                actual_key = "tab_switch_2nd"
                note = "Second tab switch detected."
            else:
                actual_key = "tab_switch_3rd_plus"
                note = f"Tab switch #{self._tab_switch_count} detected."
        else:
            actual_key = signal_key
            note = metadata.get("note", f"Signal recorded: {signal_key}")

        deduction = SIGNAL_WEIGHTS.get(actual_key, 0)
        self.score = max(0, self.score - deduction)

        entry = {
            "signal": actual_key,
            "deduction": deduction,
            "score_after": self.score,
            "note": note,
            "timestamp": ts,
            "metadata": metadata,
        }
        self.signals.append(entry)
        logger.info(
            f"[Integrity] {self.candidate_id} | {actual_key} | "
            f"-{deduction}pts | Score now: {self.score}"
        )
        return {"deducted": deduction, "new_score": self.score, "note": note}

    def check_gpt_syntax(self, transcript: str, question_number: int) -> dict:
        """
        Checks an answer for GPT syntax. If suspected:
        - Sets a "challenge pending" flag (caller must fire a verification question)
        - Does NOT deduct score yet
        Returns {"challenge_required": bool, "matched_patterns": list}
        """
        result = detect_gpt_syntax(transcript)
        if not result["suspected"]:
            return {"challenge_required": False, "matched_patterns": []}

        self._gpt_suspected_count += 1
        self._gpt_challenge_pending = True
        self.record_signal("gpt_syntax_suspected", {
            "note": f"GPT syntax patterns detected. Challenge fired. Q#{question_number}.",
            "patterns": result["matched_patterns"],
        })
        return {
            "challenge_required": True,
            "matched_patterns": result["matched_patterns"],
            "challenge_prompt": (
                "That was interesting. Could you elaborate by walking me through "
                "a real scenario where you personally applied this? "
                "Describe the specific problem you faced and the exact steps you took."
            )
        }

    def confirm_gpt_challenge_result(self, candidate_passed: bool, score: int) -> None:
        """
        Called after the follow-up challenge question is answered.
        - If candidate passes (score ≥ 5): they're clean, challenge clears.
        - If candidate fails (score < 5): confirm GPT signal, deduct score.
        """
        self._gpt_challenge_pending = False
        if candidate_passed or score >= 5:
            # Clean — no deduction
            self.record_signal("gpt_challenge_cleared", {
                "note": "Challenge passed. GPT suspicion cleared. No deduction."
            })
        else:
            # Failed challenge — confirmed GPT use
            self.record_signal("gpt_syntax_confirmed", {
                "note": f"Challenge failed (score {score}/10). GPT use confirmed."
            })

    def record_resume_challenge(self, skill_claim: str, passed: bool, score: int) -> None:
        """
        Records a resume claim verification attempt.
        First failure for a claim: grace period, no deduction.
        Second consecutive failure on the SAME claim: deduction applied.
        """
        if skill_claim not in self._resume_fail_streak:
            self._resume_fail_streak[skill_claim] = 0

        if passed or score >= 5:
            self._resume_fail_streak[skill_claim] = 0  # Reset streak on pass
            self.record_signal("resume_challenge_cleared", {
                "note": f"Resume claim '{skill_claim[:50]}' verified successfully."
            })
        else:
            self._resume_fail_streak[skill_claim] += 1
            streak = self._resume_fail_streak[skill_claim]

            if streak == 1:
                self.record_signal("resume_challenge_fail_1", {
                    "note": f"First failure on '{skill_claim[:50]}'. Grace period — no deduction."
                })
            else:
                self.record_signal("resume_challenge_fail_2", {
                    "note": f"Second consecutive failure on '{skill_claim[:50]}'. Deduction applied."
                })

    def check_behavioral_flags(
        self,
        avg_wpm: float,
        total_filler_words: int,
        robotically_structured_count: int,
        total_answers: int,
    ) -> None:
        """
        Evaluate behavioral telemetry at end of interview.
        These signals are weak individually and only fire in combination.
        """
        if total_answers < 3:
            return  # Too few answers to assess behavior reliably

        # Check for abnormally fast speech (likely reading from script)
        if avg_wpm > 280:
            self.record_signal("abnormally_fast_wpm", {
                "note": f"Average WPM {avg_wpm:.0f} (>280) — possible script reading."
            })

        # Check for zero filler words across entire interview (unnaturally clean)
        if total_filler_words == 0 and total_answers >= 5:
            self.record_signal("zero_filler_words", {
                "note": "Zero filler words detected across all answers. Possibly scripted."
            })

        # Check if candidate used robotically perfect structure every time
        if total_answers >= 4 and robotically_structured_count >= total_answers * 0.85:
            self.record_signal("perfect_structure_every", {
                "note": f"{robotically_structured_count}/{total_answers} answers were robotically structured."
            })

    def compute_final(self) -> dict:
        """
        Compute the final integrity verdict.
        Returns a complete integrity report dict.
        """
        score = max(0, min(100, self.score))

        if score >= 90:
            verdict = "CLEAN"
            verdict_label = "✅ Clean"
            verdict_color = "green"
            recommendation = "No integrity concerns. Proceed to next round."
        elif score >= 70:
            verdict = "BORDERLINE"
            verdict_label = "🟡 Borderline"
            verdict_color = "yellow"
            recommendation = "Minor flags detected. Human review recommended before advancing."
        elif score >= 50:
            verdict = "FLAGGED"
            verdict_label = "🟠 Flagged"
            verdict_color = "orange"
            recommendation = (
                "Multiple integrity signals detected. Human review REQUIRED. "
                "Do NOT auto-advance. Recruiter must review signal log below."
            )
        else:
            verdict = "HIGH_RISK"
            verdict_label = "🔴 High Risk"
            verdict_color = "red"
            recommendation = (
                "Strong evidence of academic dishonesty. "
                "Human must review ALL signals and make final decision. "
                "Algorithm does NOT auto-reject — recruiter override available."
            )

        # Build human-readable signal summary
        significant_signals = [
            s for s in self.signals
            if s["deduction"] > 0 and not s["signal"].endswith("_cleared")
        ]

        return {
            "integrity_score": score,
            "integrity_verdict": verdict,
            "integrity_verdict_label": verdict_label,
            "integrity_verdict_color": verdict_color,
            "integrity_recommendation": recommendation,
            "signal_count": len(significant_signals),
            "signal_log": self.signals,  # Full audit log
            "significant_signals": significant_signals,
            "total_tab_switches": self._tab_switch_count,
            "gpt_suspected_count": self._gpt_suspected_count,
            "computed_at": ist_isoformat(),
            # Human override fields (set by recruiter, not algorithm)
            "human_override": None,       # "APPROVED" | "REJECTED" | None
            "human_override_by": None,
            "human_override_note": None,
        }


# ── Module-level convenience functions ───────────────────────────────────────

def score_band(integrity_score: int) -> str:
    """Return the band label for a given integrity score."""
    if integrity_score >= 90:
        return "CLEAN"
    elif integrity_score >= 70:
        return "BORDERLINE"
    elif integrity_score >= 50:
        return "FLAGGED"
    return "HIGH_RISK"


def format_signal_for_display(signal: dict) -> str:
    """Format a single signal log entry for recruiter display."""
    ts = signal.get("timestamp", "")[:19].replace("T", " ")
    deduction = signal.get("deduction", 0)
    deduction_str = f" (-{deduction} pts)" if deduction > 0 else " (no deduction)"
    return f"{ts} — {signal.get('note', signal.get('signal'))}{deduction_str}"
